global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'matras-api'
    static_configs:
      - targets: ['host.docker.internal:7070']  # Для Windows и macOS
      # - targets: ['host.docker.internal:7070']  # Для Linux можно использовать IP-адрес хоста

  - job_name: 'crm-users'
    static_configs:
      - targets: ['host.docker.internal:4002']  # Для Windows и macOS
      # - targets: ['host.docker.internal:7070']  # Для Linux можно использовать IP-адрес хоста

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx_with_body ]
    static_configs:
      - targets:
        - http://users_local:4002/ping
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - target_label: instance
        replacement: users_local:7070
      - target_label: __address__
        replacement: blackbox-exporter:9115